"""PyTorch 学习层：批处理、状态编码网络与训练算法。"""

from .batching import (
    ActionMaskBatch,
    ObservationBatch,
    ObservationBatchError,
    ObservationSpec,
)
from .encoder import StateEncoder, StateEncoderConfig, StateEncoding
from .evaluate import (
    EvaluationSummary,
    PolicyEpisode,
    PolicyTraceStep,
    evaluate_policy,
    play_policy,
)
from .policy import (
    ActionBatch,
    ActionPolicy,
    ActorCritic,
    ActorCriticEvaluation,
    ActorCriticOutput,
    ActorCriticSample,
    PolicyEvaluation,
    PolicyLogits,
    PolicySample,
)
from .ppo import PPOConfig, PPOTrainer, PPOUpdateMetrics
from .rollout import RolloutBatch, RolloutBuffer, RolloutStep
from .imitation import (
    BehaviorCloningConfig,
    BehaviorCloningMetrics,
    DAggerConfig,
    DAggerPPOTrainingConfig,
    DAggerPPOTrainingResult,
    DAggerRoundMetrics,
    DAggerTrainingResult,
    DemonstrationBuffer,
    ImitationExample,
    load_dagger_ppo_config,
    train_behavior_cloning,
    train_dagger_ppo,
)
from .train import (
    PPOTrainingConfig,
    TrainingResult,
    TrainingSnapshot,
    load_training_config,
    save_checkpoint,
    train_ppo,
)

__all__ = [
    "ActionMaskBatch",
    "ActionBatch",
    "ActionPolicy",
    "ActorCritic",
    "ActorCriticEvaluation",
    "ActorCriticOutput",
    "ActorCriticSample",
    "EvaluationSummary",
    "ObservationBatch",
    "ObservationBatchError",
    "ObservationSpec",
    "PPOConfig",
    "PPOTrainer",
    "PPOTrainingConfig",
    "PPOUpdateMetrics",
    "BehaviorCloningConfig",
    "BehaviorCloningMetrics",
    "DAggerConfig",
    "DAggerPPOTrainingConfig",
    "DAggerPPOTrainingResult",
    "DAggerRoundMetrics",
    "DAggerTrainingResult",
    "DemonstrationBuffer",
    "ImitationExample",
    "PolicyEpisode",
    "PolicyTraceStep",
    "StateEncoder",
    "StateEncoderConfig",
    "StateEncoding",
    "PolicyEvaluation",
    "PolicyLogits",
    "PolicySample",
    "RolloutBatch",
    "RolloutBuffer",
    "RolloutStep",
    "TrainingResult",
    "TrainingSnapshot",
    "evaluate_policy",
    "load_training_config",
    "play_policy",
    "save_checkpoint",
    "train_ppo",
    "load_dagger_ppo_config",
    "train_behavior_cloning",
    "train_dagger_ppo",
]
