"""交易游戏的纯领域核心。"""

from .catalog import Catalog, CatalogDataError, load_catalog, load_default_catalog
from .commands import (
    Borrow,
    Buy,
    BuyTruck,
    Command,
    CommandType,
    CommandValidationError,
    NextDay,
    RepairTruck,
    Repay,
    Sell,
    Travel,
)
from .inventory import add_cargo, cargo_quantity, free_capacity, remove_cargo_fifo
from .finance import assessed_assets, available_credit, borrow, repay, total_debt, total_principal
from .models import (
    CargoLot,
    City,
    CityProductKey,
    GameEndReason,
    GameMode,
    GameOutcome,
    GameState,
    Loan,
    MarketBulletin,
    MarketEvent,
    MarketEventKind,
    MarketMessage,
    MarketRole,
    MarketState,
    PlayerState,
    Product,
    ProductCategory,
    Route,
    SpecialtyScope,
    TransportMode,
)
from .price_functions import can_purchase, money, price_adjustment, purchase_unit_price, sale_unit_price, trade_total
from .results import CommandRejection, CommandResult, GameEvent, RejectionCode
from .rules import (
    FinanceRules,
    GameLimits,
    GameRules,
    GameRulesError,
    InitialStateRules,
    MarketRules,
    PricingRules,
    SettlementRules,
    TransportLossRules,
    TransportModeRules,
    TransportRules,
    VehicleRules,
    load_default_game_rules,
    load_game_rules,
)
from .session import GameSession, create_game_session
from .settlement import conclude_if_needed, is_bankrupt, settlement_assets
from .setup import create_initial_state
from .timeflow import market_bulletins, market_messages, settle_elapsed_days
from .trading import SaleQuote, buy, quote_sale, sell
from .transport import (
    RouteNotFound,
    TravelQuote,
    quote_travel,
    reference_sale_origin,
    remote_sale_distance_premium,
    shortest_distance,
    shortest_distance_any,
    travel,
)
from .vehicles import buy_truck, repair_truck

__all__ = [
    "Borrow",
    "Buy",
    "BuyTruck",
    "CargoLot",
    "Catalog",
    "CatalogDataError",
    "City",
    "CityProductKey",
    "Command",
    "CommandRejection",
    "CommandResult",
    "CommandType",
    "CommandValidationError",
    "GameEvent",
    "GameEndReason",
    "GameLimits",
    "GameMode",
    "GameOutcome",
    "GameRules",
    "GameRulesError",
    "GameState",
    "GameSession",
    "FinanceRules",
    "InitialStateRules",
    "Loan",
    "MarketBulletin",
    "MarketEvent",
    "MarketEventKind",
    "MarketMessage",
    "MarketRole",
    "MarketState",
    "MarketRules",
    "NextDay",
    "PlayerState",
    "PricingRules",
    "Product",
    "ProductCategory",
    "RejectionCode",
    "RepairTruck",
    "Repay",
    "Route",
    "RouteNotFound",
    "SaleQuote",
    "Sell",
    "SettlementRules",
    "SpecialtyScope",
    "TransportLossRules",
    "TransportMode",
    "TransportModeRules",
    "TransportRules",
    "Travel",
    "TravelQuote",
    "VehicleRules",
    "add_cargo",
    "assessed_assets",
    "available_credit",
    "borrow",
    "buy",
    "buy_truck",
    "can_purchase",
    "cargo_quantity",
    "conclude_if_needed",
    "create_initial_state",
    "create_game_session",
    "free_capacity",
    "is_bankrupt",
    "load_catalog",
    "load_default_catalog",
    "load_default_game_rules",
    "load_game_rules",
    "money",
    "market_bulletins",
    "market_messages",
    "price_adjustment",
    "purchase_unit_price",
    "quote_travel",
    "quote_sale",
    "reference_sale_origin",
    "remote_sale_distance_premium",
    "repay",
    "remove_cargo_fifo",
    "repair_truck",
    "sale_unit_price",
    "settlement_assets",
    "settle_elapsed_days",
    "sell",
    "shortest_distance",
    "shortest_distance_any",
    "trade_total",
    "total_debt",
    "total_principal",
    "travel",
]
