"""交易游戏的纯领域核心。"""

from .catalog import Catalog, CatalogDataError, load_catalog, load_default_catalog
from .commands import (
    Borrow,
    Buy,
    BuyTruck,
    Command,
    CommandType,
    CommandValidationError,
    NextDay,
    RepairTruck,
    Repay,
    Sell,
    Travel,
)
from .inventory import add_cargo, cargo_quantity, free_capacity, remove_cargo_fifo
from .models import (
    CargoLot,
    City,
    CityProductKey,
    GameMode,
    GameState,
    Loan,
    MarketState,
    PlayerState,
    Product,
    ProductCategory,
    Route,
    SpecialtyScope,
    TransportMode,
)
from .price_functions import can_purchase, money, price_lambda, purchase_unit_price, sale_unit_price, trade_total
from .results import CommandRejection, CommandResult, GameEvent, RejectionCode
from .rules import (
    GameLimits,
    GameRules,
    GameRulesError,
    InitialStateRules,
    PricingRules,
    TransportLossRules,
    TransportModeRules,
    TransportRules,
    VehicleRules,
    load_default_game_rules,
    load_game_rules,
)
from .setup import create_initial_state
from .trading import buy, sell
from .transport import (
    RouteNotFound,
    TravelQuote,
    quote_travel,
    remote_sale_distance_multiplier,
    shortest_distance,
    shortest_distance_any,
    travel,
)
from .vehicles import buy_truck, repair_truck

__all__ = [
    "Borrow",
    "Buy",
    "BuyTruck",
    "CargoLot",
    "Catalog",
    "CatalogDataError",
    "City",
    "CityProductKey",
    "Command",
    "CommandRejection",
    "CommandResult",
    "CommandType",
    "CommandValidationError",
    "GameEvent",
    "GameLimits",
    "GameMode",
    "GameRules",
    "GameRulesError",
    "GameState",
    "InitialStateRules",
    "Loan",
    "MarketState",
    "NextDay",
    "PlayerState",
    "PricingRules",
    "Product",
    "ProductCategory",
    "RejectionCode",
    "RepairTruck",
    "Repay",
    "Route",
    "RouteNotFound",
    "Sell",
    "SpecialtyScope",
    "TransportLossRules",
    "TransportMode",
    "TransportModeRules",
    "TransportRules",
    "Travel",
    "TravelQuote",
    "VehicleRules",
    "add_cargo",
    "buy",
    "buy_truck",
    "can_purchase",
    "cargo_quantity",
    "create_initial_state",
    "free_capacity",
    "load_catalog",
    "load_default_catalog",
    "load_default_game_rules",
    "load_game_rules",
    "money",
    "price_lambda",
    "purchase_unit_price",
    "quote_travel",
    "remote_sale_distance_multiplier",
    "remove_cargo_fifo",
    "repair_truck",
    "sale_unit_price",
    "sell",
    "shortest_distance",
    "shortest_distance_any",
    "trade_total",
    "travel",
]
