"""交易游戏的纯领域核心。"""

from .catalog import Catalog, CatalogDataError, load_catalog, load_default_catalog
from .commands import (
    Borrow,
    Buy,
    BuyTruck,
    Command,
    CommandType,
    CommandValidationError,
    NextDay,
    RepairTruck,
    Repay,
    Sell,
    Travel,
)
from .models import (
    CargoLot,
    CityProductKey,
    City,
    GameMode,
    GameState,
    Loan,
    MarketState,
    PlayerState,
    Product,
    ProductCategory,
    Route,
    SpecialtyScope,
    TransportMode,
)
from .inventory import add_cargo, cargo_quantity, free_capacity, remove_cargo_fifo
from .price_functions import can_purchase, money, price_lambda, purchase_unit_price, sale_unit_price, trade_total
from .setup import DEFAULT_NEW_GAME_CONFIG, NewGameConfig, create_initial_state
from .results import CommandRejection, CommandResult, GameEvent, RejectionCode
from .trading import buy, sell

__all__ = [
    "Catalog",
    "CatalogDataError",
    "Borrow",
    "Buy",
    "BuyTruck",
    "CityProductKey",
    "CargoLot",
    "Command",
    "CommandRejection",
    "CommandResult",
    "CommandType",
    "CommandValidationError",
    "City",
    "DEFAULT_NEW_GAME_CONFIG",
    "GameMode",
    "GameState",
    "Loan",
    "MarketState",
    "NewGameConfig",
    "NextDay",
    "PlayerState",
    "Product",
    "ProductCategory",
    "Route",
    "GameEvent",
    "RejectionCode",
    "RepairTruck",
    "Repay",
    "Sell",
    "SpecialtyScope",
    "TransportMode",
    "Travel",
    "add_cargo",
    "buy",
    "can_purchase",
    "cargo_quantity",
    "create_initial_state",
    "free_capacity",
    "load_catalog",
    "load_default_catalog",
    "money",
    "price_lambda",
    "purchase_unit_price",
    "remove_cargo_fifo",
    "sale_unit_price",
    "sell",
    "trade_total",
]
